// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

var form = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.maxWidth(Css.px(700)),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* form */form];

function pokemon(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* number */Json_decode.field("id", Json_decode.$$int, json)
        ];
}

var Decode = /* module */[/* pokemon */pokemon];

function AddPokemon(Props) {
  var addHandler = Props.addHandler;
  var match = React.useState((function () {
          return "";
        }));
  var setName = match[1];
  var name = match[0];
  var handleSubmit = function (e) {
    e.preventDefault();
    fetch("https://pokeapi.co/api/v2/pokemon/" + name).then((function (prim) {
                return prim.json();
              })).then((function (json) {
              return Promise.resolve(Curry._1(addHandler, pokemon(json)));
            })).catch((function (e) {
            return Promise.resolve((console.log(e), /* () */0));
          }));
    return Curry._1(setName, (function (param) {
                  return "";
                }));
  };
  return React.createElement("form", {
              className: form,
              onSubmit: handleSubmit
            }, React.createElement("input", {
                  placeholder: "Enter a pokemon...",
                  value: name,
                  onChange: (function (e) {
                      return Curry._1(setName, e.target.value);
                    })
                }), React.createElement("input", {
                  type: "submit",
                  value: "Add"
                }));
}

var make = AddPokemon;

export {
  Styles ,
  Decode ,
  make ,
  
}
/* form Not a pure module */
