// Generated by BUCKLESCRIPT VERSION 5.0.5, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function AddPokemon(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setName = match[1];
  var name = match[0];
  var handleSubmit = function (e) {
    e.preventDefault();
    return Curry._1(setName, (function (param) {
                  return "";
                }));
  };
  return React.createElement("form", {
              onSubmit: handleSubmit
            }, React.createElement("input", {
                  placeholder: "Enter a pokemon...",
                  value: name,
                  onChange: (function (e) {
                      return Curry._1(setName, e.target.value);
                    })
                }), React.createElement("input", {
                  type: "submit",
                  value: "Add"
                }), React.createElement("h1", undefined, name));
}

var make = AddPokemon;

export {
  make ,
  
}
/* react Not a pure module */
