// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function AddPokemon(Props) {
  var addHandler = Props.addHandler;
  var match = React.useState((function () {
          return "";
        }));
  var setName = match[1];
  var name = match[0];
  var handleSubmit = function (e) {
    e.preventDefault();
    Curry._1(addHandler, name);
    return Curry._1(setName, (function (param) {
                  return "";
                }));
  };
  return React.createElement("form", {
              onSubmit: handleSubmit
            }, React.createElement("input", {
                  placeholder: "Enter a pokemon...",
                  value: name,
                  onChange: (function (e) {
                      return Curry._1(setName, e.target.value);
                    })
                }), React.createElement("input", {
                  type: "submit",
                  value: "Add"
                }));
}

var make = AddPokemon;

exports.make = make;
/* react Not a pure module */
