// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var V4 = require("uuid/v4");
var Party$Pokemon = require("./Party.bs.js");
var AddPokemon$Pokemon = require("./AddPokemon.bs.js");

function App(Props) {
  var match = React.useReducer((function (state, action) {
          if (action.tag) {
            var id = action[0];
            return /* record */[/* party */List.filter((function (p) {
                              return p[/* id */1] !== id;
                            }))(state[/* party */0])];
          } else {
            return /* record */[/* party : :: */[
                      /* record */[
                        /* name */action[0],
                        /* id */V4()
                      ],
                      state[/* party */0]
                    ]];
          }
        }), /* record */[/* party : [] */0]);
  var dispatch = match[1];
  return React.createElement("div", undefined, React.createElement(AddPokemon$Pokemon.make, {
                  addHandler: (function (p) {
                      return Curry._1(dispatch, /* Add */Block.__(0, [p]));
                    })
                }), React.createElement(Party$Pokemon.make, {
                  party: match[0][/* party */0],
                  removeHandler: (function (id) {
                      return Curry._1(dispatch, /* Remove */Block.__(1, [id]));
                    })
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
