// Generated by BUCKLESCRIPT VERSION 5.0.5, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Party$Pokemon from "./Party.bs.js";
import * as AddPokemon$Pokemon from "./AddPokemon.bs.js";

function App(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* pokemon : :: */[
                    action[0],
                    state[/* pokemon */0]
                  ]];
        }), /* record */[/* pokemon : [] */0]);
  var dispatch = match[1];
  return React.createElement("div", undefined, React.createElement(AddPokemon$Pokemon.make, {
                  addHandler: (function (p) {
                      return Curry._1(dispatch, /* Add */[p]);
                    })
                }), React.createElement(Party$Pokemon.make, {
                  pokemon: match[0][/* pokemon */0]
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
