// Generated by BUCKLESCRIPT VERSION 5.0.5, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Pokemon$Pokemon from "./Pokemon.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Pokemon$Pokemon.make, { }), "app");

export {
  
}
/*  Not a pure module */
