// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$Pokemon = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$Pokemon.make, { }), "app");

/*  Not a pure module */
