// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$Pokemon from "./App.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$Pokemon.make, { }), "app");

export {
  
}
/*  Not a pure module */
