// Generated by BUCKLESCRIPT VERSION 5.0.5, PLEASE EDIT WITH CARE

import * as React from "react";

function Party(Props) {
  return React.createElement("div", undefined);
}

var make = Party;

export {
  make ,
  
}
/* react Not a pure module */
