// Generated by BUCKLESCRIPT VERSION 5.0.5, PLEASE EDIT WITH CARE

import * as React from "react";

function Pokemon(Props) {
  return React.createElement("h1", undefined, "helssslo");
}

var make = Pokemon;

export {
  make ,
  
}
/* react Not a pure module */
