// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Pokemon(Props) {
  return React.createElement("h1", undefined, "Hello");
}

var make = Pokemon;

export {
  make ,
  
}
/* react Not a pure module */
