// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Pokemon(Props) {
  return React.createElement("h1", undefined, "Hello");
}

var make = Pokemon;

exports.make = make;
/* react Not a pure module */
